### ISSUE TITLE
关于pr曲线

### ISSUE THREAD

**Issue by Wangpeiyi9979** [Spico197/NYT-H#1]
您好，很感谢您的工作，想请问一下`evaluate.py`文件中，生成了多个有关prc的json文件。
分别是：'prc_skprc_mine.json'，"prc.json"，"prc_opennre.json"， "b_prc_opennre.json"，"prc_bag2sent.json"。想请问一下它们分别都是什么？？

**Comment by Spico197** [comment]
抱歉代码里可能有点乱，后面会重构一下。这其实是个PRC绘制的坑，PRC是有很多种绘制方法的。我在编码的时候也是边尝试边写的，所以包含了一些没有删掉的过程。PRC根据是否包含NA关系以及是否包含所有的预测输出，可以分为4种。

- 不包含NA，取最大预测输出：修改`evaluate.py`中第166行的`for`语句，改为最大概率/logits位置的结果。
- 不包含NA，取全部预测输出：我们最终在论文中汇报的是OpenNRE绘制方案的结果，即DSGT上的PRC：`prc_opennre.json`和MAGT上的PRC：`b_prc_opennre.json`。如README中所述，这种PRC的绘制方案是将所有logits/概率 进行排序（假如有N个instance，每个instance预测输出21个非NA关系的概率，那么就会有N*21个点）。
- 包含NA，取最大预测输出：`prc.json`文件中的PRC结果是对每个instance的输出结果，只取最大logits/概率 进行排序，最终只有N个点（DSGT）。论文中未汇报。
- 包含NA，取全部预测输出：去除`evaluate.py`文件第167行的`if`条件。

其它的几个文件：
- `prc_bag2sent.json`：bag2sent track的DSGT PRC结果，论文中未汇报。
- `prc_skprc_mine.json`：早期使用sklearn求解PRC的一个尝试，需要将多分类预测结果先转换为二分类结果（对/错），论文中未汇报。

**Comment by Wangpeiyi9979** [comment]
感谢！
