### ISSUE TITLE
Bag2Bag Track中貌似存在Bug

### ISSUE THREAD

**Issue by tmliang** [Spico197/NYT-H#6]
在如下代码中, 计算Bag2Bag的precision, recall和F1 score时, 统计的是句子数量, 而不是Bag的数量
https://github.com/Spico197/NYT-H/blob/7eeca3a85c998b2b3ec588986b3e0abd69e1b15d/evaluate.py#L721-L724
和论文Eq.(1)中对N<sub>r</sub>, N<sub>sys</sub>, N<sub>data</sub>所述不符. 请问一下是不是代码的Bug?

**Comment by Spico197** [comment]
非常感谢您对本工作的关注。经过再次检查之后，确认MAGT评价部分代码和论文中的公式存在差异，在此向您和其他关注本工作的学者表示歉意。严格来说，统计的并不是句子的结果（每个包中各个句子的预测结果保持一致），而是将每个包的1个结果记录成了`k_i`个结果，`k_i`为第`i`个包的句子数量。如果任意`k_i`相等时，结果不会变化。

为与论文中的公式保持一致，请将`evaluate.py`文件的`compute_magt`函数按如下方式修改：

将
https://github.com/Spico197/NYT-H/blob/7eeca3a85c998b2b3ec588986b3e0abd69e1b15d/evaluate.py#L706-L709
修改为
```python
bag_ids = set()
for ins in test:
    if track in {"bag", "bag2bag"}:
        if ins[id_name] not in bag_ids:
            bag_ids.add(ins[id_name])
        else:
            continue
    if ins['bag_label'] == 'yes':
        stat_results[ins['relation']]['labels'].append(1)
```

同时，经过重新评测之后，MAGT的P、R、F1值会有变化，但最终排序的结论仍然保持不变。再次向您表示感谢。
