### ISSUE TITLE
关于对Bag进行分组的方式

### ISSUE THREAD

**Issue by tmliang** [Spico197/NYT-H#7]
你好！在OpenNRE中，根据 (head, tail, rel) 对 training set 进行分组，根据 (head, tail) 对test set 进行分组。但是在 NYT-H 的training set中，好像也是根据 (head, tail) 进行分组的。比如 id 为 "NONNATRAIN#77529" 的 Bag 中，同时包含2种不同的关系。这会导致某些关系类别的训练样本变少, 因为每个 Bag 只取其中的一个样本的 rel 作为整个 Bag 的 rel

**Comment by Spico197** [comment]
您好。本工作的主要目的在于分享新的数据集并探索DS噪声数据对评价结果的影响。因此在包的构建过程中，我们与DS的原始假设保持一致，仅使用头尾两实体作为包构建的依据。

**Comment by tmliang** [comment]
了解，感谢！
