### ISSUE TITLE
Are missing label considered for test set?

### ISSUE THREAD

**Issue by rivercold** [Spico197/NYT-H#8]
Your paper states that sentences were annotated manually in a binary strategy. Did you provide only the relations that are distantly labeled positive or all 22 relation candidates for annotators? If the former, how do you justify the claim "the new test set does not have the FP and **FN** problem which are often occurred in the DS-constructed data"? I think some missing labels may occur due to the incompleteness of KB. 

Thank you!

**Comment by Spico197** [comment]
Hi there, thanks for your attention on this work. 

- We split the former NYT10 dataset and annotate the new test set in a binary strategy. The number of relation really does not matter to the binary annotation process. Please refer to section 3 for more details.
- There is no evaluation noise in NYT-H test set, and we can get accurate evaluation results. There are lots of FN noises in NA instances, and NA instance is not in the test set, so there is no FN noise in the test set.

Hope this could answer your question. If you have further questions, feel free to reopen this issue.

**Comment by rivercold** [comment]
Thank you for the response! I did check Section 3, but am still unclear about the following statement in Section 3.2: 

> The sentences are annotated manually in a binary strategy, which is to decide whether the sentences express the relations assigned by DS. It is difficult to pick out one from over 50 types of relations, so we decide to use the binary strategy. If a sentence actually expresses the DS-annotated relation for the given entity pair....

I don't quite understand why "The number of relation really does not matter to the binary annotation process". Suppose there are K classes in a multi-label scenario, you do need to check each instance in binary process for K times, right? But the claim "If a sentence actually expresses the DS-annotated relation for the given entity pair..."  looks like annotations only happen on those positive labels held by DS, not all K classes?

**Comment by Spico197** [comment]
No, every instance will be checked for only **ONCE** under the binary strategy, not K times for all labels in the candidate relation set. It is to annotate whether the distantly-supervised label is right or not.

For example:
```
DS label: founder_of
Sentence: [Steve Jobs] left [Apple].

Manual Annotation: NO
```

**Comment by rivercold** [comment]
Thank you! I think you do hold an assumption that _if there exists at least one distant relation between an entity pair, there are no missing labels between them_? 

Regarding "every instance will be checked only **ONCE**", I do observe some instances (sentences) are labeled multiple times (not just on bag-level), e.g., 
> _Belarus_	_Minsk_	/location/location/contains	At a conference just last week in Minsk , capital of the neighboring republic of Belarus , Mr. Ustinov declared that the fight was unending .
> _Belarus_	_Minsk_	/location/country/capital	At a conference just last week in Minsk , capital of the neighboring republic of Belarus , Mr. Ustinov declared that the fight was unending . '

My question: How should we handle those cases for **sentence-level classification** and its evaluation? I saw your codes use softmax or max function (https://github.com/Spico197/NYT-H/blob/09b0094c90ac85cf12b8064a76a4f40e26433cb5/evaluate.py#L157), do you think the multi-class setting is still the best choice here?

**Comment by Spico197** [comment]
- You can take the missing relations as NA relation. If one sentence is annotated as relation R by DS, and labeled as NO by manual check, it can express any other relations except R, maybe NA.
- In sent2sent track, suppose NYT-H is equivalent to SemEval2010 Task8 and TACRED, we just use the softmax to get the most possible relation for each instance. You can do it under the multi-class multi-label scenario, but the number of instances with more than one relations is not that big, refering to section 3.4 and table 3.
